### PR TITLE
Update reproject version to v0.3.2

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - could you push the merge button here?

**Comment by bsipocz** [comment]
ping @astrofrog or @mwcraig to merge this.

**Comment by mwcraig** [comment]
Thanks, @bsipocz!

**Comment by mwcraig** [comment]
Just thought of a question -- is there a minimum version of numpy that should be imposed here?

**Pull request merged**
