### PR TITLE
Re-render feedstock to include Python 3.7

### PR DESCRIPTION
**Pull request by astrofrog**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - if you like, you can add me as a maintainer here

**Comment by cdeil** [comment]
@astrofrog - Thanks!

All builds are green - merge?

**Comment by astrofrog** [comment]
@cdeil - no, this hasn't actually worked in the sense the Python 3.7 build hasn't been added

**Comment by astrofrog** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
